// SiYuan - Refactor your thinking
// Copyright (c) 2020-present, b3log.org
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package api

import (
	"github.com/gin-gonic/gin"
	"github.com/siyuan-note/siyuan/kernel/model"
)

func ServeAPI(ginServer *gin.Engine) {
	// 不需要鉴权

	ginServer.Handle("GET", "/api/system/bootProgress", bootProgress)
	ginServer.Handle("POST", "/api/system/bootProgress", bootProgress)
	ginServer.Handle("GET", "/api/system/version", version)
	ginServer.Handle("POST", "/api/system/version", version)
	ginServer.Handle("POST", "/api/system/currentTime", currentTime)
	ginServer.Handle("POST", "/api/system/uiproc", addUIProcess)
	ginServer.Handle("POST", "/api/system/loginAuth", model.LoginAuth)
	ginServer.Handle("POST", "/api/system/logoutAuth", model.LogoutAuth)
	ginServer.Handle("GET", "/api/system/getCaptcha", model.GetCaptcha)
	ginServer.Handle("GET", "/api/icon/getDynamicIcon", getDynamicIcon)

	// 需要鉴权

	ginServer.Handle("POST", "/api/system/getEmojiConf", model.CheckWebAuth, getEmojiConf)
	ginServer.Handle("POST", "/api/system/setAPIToken", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAPIToken)
	ginServer.Handle("POST", "/api/system/setAccessAuthCode", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAccessAuthCode)
	ginServer.Handle("POST", "/api/system/setFollowSystemLockScreen", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setFollowSystemLockScreen)
	ginServer.Handle("POST", "/api/system/setNetworkServe", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setNetworkServe)
	ginServer.Handle("POST", "/api/system/setAutoLaunch", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAutoLaunch)
	ginServer.Handle("POST", "/api/system/setDownloadInstallPkg", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setDownloadInstallPkg)
	ginServer.Handle("POST", "/api/system/setNetworkProxy", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setNetworkProxy)
	ginServer.Handle("POST", "/api/system/setWorkspaceDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setWorkspaceDir)
	ginServer.Handle("POST", "/api/system/getWorkspaces", model.CheckWebAuth, getWorkspaces)
	ginServer.Handle("POST", "/api/system/getMobileWorkspaces", model.CheckWebAuth, getMobileWorkspaces)
	ginServer.Handle("POST", "/api/system/checkWorkspaceDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, checkWorkspaceDir)
	ginServer.Handle("POST", "/api/system/createWorkspaceDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createWorkspaceDir)
	ginServer.Handle("POST", "/api/system/removeWorkspaceDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeWorkspaceDir)
	ginServer.Handle("POST", "/api/system/removeWorkspaceDirPhysically", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeWorkspaceDirPhysically)
	ginServer.Handle("POST", "/api/system/setAppearanceMode", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAppearanceMode)
	ginServer.Handle("POST", "/api/system/setUILayout", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setUILayout)
	ginServer.Handle("POST", "/api/system/getSysFonts", model.CheckWebAuth, getSysFonts)
	ginServer.Handle("POST", "/api/system/exit", model.CheckWebAuth, model.CheckAdminRole, exit)
	ginServer.Handle("POST", "/api/system/getConf", model.CheckWebAuth, getConf)
	ginServer.Handle("POST", "/api/system/checkUpdate", model.CheckWebAuth, model.CheckAdminRole, checkUpdate)
	ginServer.Handle("POST", "/api/system/exportLog", model.CheckWebAuth, model.CheckAdminRole, exportLog)
	ginServer.Handle("POST", "/api/system/getChangelog", model.CheckWebAuth, getChangelog)
	ginServer.Handle("POST", "/api/system/getNetwork", model.CheckWebAuth, model.CheckAdminRole, getNetwork)
	ginServer.Handle("POST", "/api/system/exportConf", model.CheckWebAuth, model.CheckAdminRole, exportConf)
	ginServer.Handle("POST", "/api/system/importConf", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importConf)
	ginServer.Handle("POST", "/api/system/getWorkspaceInfo", model.CheckWebAuth, getWorkspaceInfo)
	ginServer.Handle("POST", "/api/system/reloadUI", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadUI) // TODO 请使用 /api/ui/reloadUI，该端点计划于 2026 年 6 月 30 日后删除 https://github.com/siyuan-note/siyuan/issues/15308#issuecomment-3077675356
	ginServer.Handle("POST", "/api/system/addMicrosoftDefenderExclusion", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, addMicrosoftDefenderExclusion)
	ginServer.Handle("POST", "/api/system/ignoreAddMicrosoftDefenderExclusion", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, ignoreAddMicrosoftDefenderExclusion)
	ginServer.Handle("POST", "/api/system/vacuumDataIndex", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, vacuumDataIndex)
	ginServer.Handle("POST", "/api/system/rebuildDataIndex", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, rebuildDataIndex)

	ginServer.Handle("POST", "/api/storage/setLocalStorage", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setLocalStorage)
	ginServer.Handle("POST", "/api/storage/getLocalStorage", model.CheckWebAuth, getLocalStorage)
	ginServer.Handle("POST", "/api/storage/setLocalStorageVal", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setLocalStorageVal)
	ginServer.Handle("POST", "/api/storage/removeLocalStorageVals", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeLocalStorageVals)
	ginServer.Handle("POST", "/api/storage/setCriterion", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setCriterion)
	ginServer.Handle("POST", "/api/storage/getCriteria", model.CheckWebAuth, getCriteria)
	ginServer.Handle("POST", "/api/storage/removeCriterion", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeCriterion)
	ginServer.Handle("POST", "/api/storage/getRecentDocs", model.CheckWebAuth, getRecentDocs)
	ginServer.Handle("POST", "/api/storage/updateRecentDocViewTime", model.CheckWebAuth, updateRecentDocViewTime)
	ginServer.Handle("POST", "/api/storage/updateRecentDocCloseTime", model.CheckWebAuth, updateRecentDocCloseTime)
	ginServer.Handle("POST", "/api/storage/updateRecentDocOpenTime", model.CheckWebAuth, updateRecentDocOpenTime)

	ginServer.Handle("POST", "/api/storage/getOutlineStorage", model.CheckWebAuth, getOutlineStorage)
	ginServer.Handle("POST", "/api/storage/setOutlineStorage", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setOutlineStorage)
	ginServer.Handle("POST", "/api/storage/removeOutlineStorage", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeOutlineStorage)

	ginServer.Handle("POST", "/api/account/login", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, login)
	ginServer.Handle("POST", "/api/account/checkActivationcode", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, checkActivationcode)
	ginServer.Handle("POST", "/api/account/useActivationcode", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, useActivationcode)
	ginServer.Handle("POST", "/api/account/deactivate", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, deactivateUser)
	ginServer.Handle("POST", "/api/account/startFreeTrial", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, startFreeTrial)

	ginServer.Handle("POST", "/api/notebook/lsNotebooks", model.CheckWebAuth, lsNotebooks)
	ginServer.Handle("POST", "/api/notebook/openNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, openNotebook)
	ginServer.Handle("POST", "/api/notebook/closeNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, closeNotebook)
	ginServer.Handle("POST", "/api/notebook/getNotebookConf", model.CheckWebAuth, getNotebookConf)
	ginServer.Handle("POST", "/api/notebook/setNotebookConf", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setNotebookConf)
	ginServer.Handle("POST", "/api/notebook/createNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createNotebook)
	ginServer.Handle("POST", "/api/notebook/removeNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeNotebook)
	ginServer.Handle("POST", "/api/notebook/renameNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameNotebook)
	ginServer.Handle("POST", "/api/notebook/changeSortNotebook", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, changeSortNotebook)
	ginServer.Handle("POST", "/api/notebook/setNotebookIcon", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setNotebookIcon)
	ginServer.Handle("POST", "/api/notebook/getNotebookInfo", model.CheckWebAuth, getNotebookInfo)

	ginServer.Handle("POST", "/api/filetree/searchDocs", model.CheckWebAuth, searchDocs)
	ginServer.Handle("POST", "/api/filetree/listDocsByPath", model.CheckWebAuth, listDocsByPath)
	ginServer.Handle("POST", "/api/filetree/getDoc", model.CheckWebAuth, getDoc)
	ginServer.Handle("POST", "/api/filetree/getDocCreateSavePath", model.CheckWebAuth, getDocCreateSavePath)
	ginServer.Handle("POST", "/api/filetree/getRefCreateSavePath", model.CheckWebAuth, getRefCreateSavePath)
	ginServer.Handle("POST", "/api/filetree/changeSort", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, changeSort)
	ginServer.Handle("POST", "/api/filetree/createDocWithMd", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createDocWithMd)
	ginServer.Handle("POST", "/api/filetree/createDailyNote", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createDailyNote)
	ginServer.Handle("POST", "/api/filetree/createDoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createDoc)
	ginServer.Handle("POST", "/api/filetree/renameDoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameDoc)
	ginServer.Handle("POST", "/api/filetree/renameDocByID", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameDocByID)
	ginServer.Handle("POST", "/api/filetree/removeDoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeDoc)
	ginServer.Handle("POST", "/api/filetree/removeDocByID", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeDocByID)
	ginServer.Handle("POST", "/api/filetree/removeDocs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeDocs)
	ginServer.Handle("POST", "/api/filetree/moveDocs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, moveDocs)
	ginServer.Handle("POST", "/api/filetree/moveDocsByID", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, moveDocsByID)
	ginServer.Handle("POST", "/api/filetree/duplicateDoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, duplicateDoc)
	ginServer.Handle("POST", "/api/filetree/getHPathByPath", model.CheckWebAuth, getHPathByPath)
	ginServer.Handle("POST", "/api/filetree/getHPathsByPaths", model.CheckWebAuth, getHPathsByPaths)
	ginServer.Handle("POST", "/api/filetree/getHPathByID", model.CheckWebAuth, getHPathByID)
	ginServer.Handle("POST", "/api/filetree/getPathByID", model.CheckWebAuth, getPathByID)
	ginServer.Handle("POST", "/api/filetree/getFullHPathByID", model.CheckWebAuth, getFullHPathByID)
	ginServer.Handle("POST", "/api/filetree/getIDsByHPath", model.CheckWebAuth, getIDsByHPath)
	ginServer.Handle("POST", "/api/filetree/doc2Heading", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, doc2Heading)
	ginServer.Handle("POST", "/api/filetree/heading2Doc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, heading2Doc)
	ginServer.Handle("POST", "/api/filetree/li2Doc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, li2Doc)
	ginServer.Handle("POST", "/api/filetree/upsertIndexes", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, upsertIndexes)
	ginServer.Handle("POST", "/api/filetree/removeIndexes", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeIndexes)
	ginServer.Handle("POST", "/api/filetree/listDocTree", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, listDocTree)
	ginServer.Handle("POST", "/api/filetree/moveLocalShorthands", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, moveLocalShorthands)
	ginServer.Handle("POST", "/api/filetree/refreshFiletree ", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, rebuildDataIndex) // TODO 请使用 /api/system/rebuildDataIndex，该端点计划于 2026 年 6 月 30 日后删除 https://github.com/siyuan-note/siyuan/issues/15663#issuecomment-3219296189

	ginServer.Handle("POST", "/api/format/autoSpace", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, autoSpace)
	ginServer.Handle("POST", "/api/format/netImg2LocalAssets", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, netImg2LocalAssets)
	ginServer.Handle("POST", "/api/format/netAssets2LocalAssets", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, netAssets2LocalAssets)

	ginServer.Handle("POST", "/api/history/getNotebookHistory", model.CheckWebAuth, model.CheckAdminRole, getNotebookHistory)
	ginServer.Handle("POST", "/api/history/rollbackNotebookHistory", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, rollbackNotebookHistory)
	ginServer.Handle("POST", "/api/history/rollbackAssetsHistory", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, rollbackAssetsHistory)
	ginServer.Handle("POST", "/api/history/getDocHistoryContent", model.CheckWebAuth, model.CheckAdminRole, getDocHistoryContent)
	ginServer.Handle("POST", "/api/history/rollbackDocHistory", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, rollbackDocHistory)
	ginServer.Handle("POST", "/api/history/clearWorkspaceHistory", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, clearWorkspaceHistory)
	ginServer.Handle("POST", "/api/history/reindexHistory", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reindexHistory)
	ginServer.Handle("POST", "/api/history/searchHistory", model.CheckWebAuth, model.CheckAdminRole, searchHistory)
	ginServer.Handle("POST", "/api/history/getHistoryItems", model.CheckWebAuth, model.CheckAdminRole, getHistoryItems)

	ginServer.Handle("POST", "/api/outline/getDocOutline", model.CheckWebAuth, getDocOutline)

	ginServer.Handle("POST", "/api/bookmark/getBookmark", model.CheckWebAuth, getBookmark)
	ginServer.Handle("POST", "/api/bookmark/renameBookmark", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameBookmark)
	ginServer.Handle("POST", "/api/bookmark/removeBookmark", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeBookmark)

	ginServer.Handle("POST", "/api/tag/getTag", model.CheckWebAuth, getTag)
	ginServer.Handle("POST", "/api/tag/renameTag", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameTag)
	ginServer.Handle("POST", "/api/tag/removeTag", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeTag)

	ginServer.Handle("POST", "/api/lute/spinBlockDOM", model.CheckWebAuth, spinBlockDOM) // 未测试
	ginServer.Handle("POST", "/api/lute/html2BlockDOM", model.CheckWebAuth, html2BlockDOM)
	ginServer.Handle("POST", "/api/lute/copyStdMarkdown", model.CheckWebAuth, copyStdMarkdown)

	ginServer.Handle("POST", "/api/query/sql", model.CheckWebAuth, SQL)
	ginServer.Handle("POST", "/api/sqlite/flushTransaction", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, flushTransaction)

	ginServer.Handle("POST", "/api/search/searchTag", model.CheckWebAuth, searchTag)
	ginServer.Handle("POST", "/api/search/searchTemplate", model.CheckWebAuth, searchTemplate)
	ginServer.Handle("POST", "/api/search/removeTemplate", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeTemplate)
	ginServer.Handle("POST", "/api/search/searchWidget", model.CheckWebAuth, searchWidget)
	ginServer.Handle("POST", "/api/search/searchRefBlock", model.CheckWebAuth, searchRefBlock)
	ginServer.Handle("POST", "/api/search/searchEmbedBlock", model.CheckWebAuth, searchEmbedBlock)
	ginServer.Handle("POST", "/api/search/getEmbedBlock", model.CheckWebAuth, getEmbedBlock)
	ginServer.Handle("POST", "/api/search/updateEmbedBlock", model.CheckWebAuth, updateEmbedBlock)
	ginServer.Handle("POST", "/api/search/fullTextSearchBlock", model.CheckWebAuth, fullTextSearchBlock)
	ginServer.Handle("POST", "/api/search/searchAsset", model.CheckWebAuth, searchAsset)
	ginServer.Handle("POST", "/api/search/findReplace", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, findReplace)
	ginServer.Handle("POST", "/api/search/fullTextSearchAssetContent", model.CheckWebAuth, fullTextSearchAssetContent)
	ginServer.Handle("POST", "/api/search/getAssetContent", model.CheckWebAuth, getAssetContent)
	ginServer.Handle("POST", "/api/search/listInvalidBlockRefs", model.CheckWebAuth, listInvalidBlockRefs)

	ginServer.Handle("POST", "/api/block/getBlockInfo", model.CheckWebAuth, getBlockInfo)
	ginServer.Handle("POST", "/api/block/getBlockDOM", model.CheckWebAuth, getBlockDOM)
	ginServer.Handle("POST", "/api/block/getBlockDOMs", model.CheckWebAuth, getBlockDOMs)
	ginServer.Handle("POST", "/api/block/getBlockDOMWithEmbed", model.CheckWebAuth, getBlockDOMWithEmbed)
	ginServer.Handle("POST", "/api/block/getBlockDOMsWithEmbed", model.CheckWebAuth, getBlockDOMsWithEmbed)
	ginServer.Handle("POST", "/api/block/getBlockKramdown", model.CheckWebAuth, getBlockKramdown)
	ginServer.Handle("POST", "/api/block/getChildBlocks", model.CheckWebAuth, getChildBlocks)
	ginServer.Handle("POST", "/api/block/getTailChildBlocks", model.CheckWebAuth, getTailChildBlocks)
	ginServer.Handle("POST", "/api/block/getBlockBreadcrumb", model.CheckWebAuth, getBlockBreadcrumb)
	ginServer.Handle("POST", "/api/block/getBlockIndex", model.CheckWebAuth, getBlockIndex)
	ginServer.Handle("POST", "/api/block/getBlocksIndexes", model.CheckWebAuth, getBlocksIndexes)
	ginServer.Handle("POST", "/api/block/getRefIDs", model.CheckWebAuth, getRefIDs)
	ginServer.Handle("POST", "/api/block/getRefIDsByFileAnnotationID", model.CheckWebAuth, getRefIDsByFileAnnotationID)
	ginServer.Handle("POST", "/api/block/getBlockDefIDsByRefText", model.CheckWebAuth, getBlockDefIDsByRefText)
	ginServer.Handle("POST", "/api/block/getRefText", model.CheckWebAuth, getRefText)
	ginServer.Handle("POST", "/api/block/getDOMText", model.CheckWebAuth, getDOMText)
	ginServer.Handle("POST", "/api/block/getTreeStat", model.CheckWebAuth, getTreeStat)
	ginServer.Handle("POST", "/api/block/getBlocksWordCount", model.CheckWebAuth, getBlocksWordCount)
	ginServer.Handle("POST", "/api/block/getContentWordCount", model.CheckWebAuth, getContentWordCount)
	ginServer.Handle("POST", "/api/block/getRecentUpdatedBlocks", model.CheckWebAuth, getRecentUpdatedBlocks)
	ginServer.Handle("POST", "/api/block/getDocInfo", model.CheckWebAuth, getDocInfo)
	ginServer.Handle("POST", "/api/block/getDocsInfo", model.CheckWebAuth, getDocsInfo)
	ginServer.Handle("POST", "/api/block/checkBlockExist", model.CheckWebAuth, checkBlockExist)
	ginServer.Handle("POST", "/api/block/getUnfoldedParentID", model.CheckWebAuth, getUnfoldedParentID)
	ginServer.Handle("POST", "/api/block/checkBlockFold", model.CheckWebAuth, checkBlockFold)
	ginServer.Handle("POST", "/api/block/insertBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, insertBlock)
	ginServer.Handle("POST", "/api/block/batchInsertBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchInsertBlock)
	ginServer.Handle("POST", "/api/block/prependBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, prependBlock)
	ginServer.Handle("POST", "/api/block/batchPrependBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchPrependBlock)
	ginServer.Handle("POST", "/api/block/appendBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, appendBlock)
	ginServer.Handle("POST", "/api/block/batchAppendBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchAppendBlock)
	ginServer.Handle("POST", "/api/block/appendDailyNoteBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, appendDailyNoteBlock)
	ginServer.Handle("POST", "/api/block/prependDailyNoteBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, prependDailyNoteBlock)
	ginServer.Handle("POST", "/api/block/updateBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, updateBlock)
	ginServer.Handle("POST", "/api/block/batchUpdateBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchUpdateBlock)
	ginServer.Handle("POST", "/api/block/deleteBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, deleteBlock)
	ginServer.Handle("POST", "/api/block/moveBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, moveBlock)
	ginServer.Handle("POST", "/api/block/moveOutlineHeading", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, moveOutlineHeading)
	ginServer.Handle("POST", "/api/block/foldBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, foldBlock)
	ginServer.Handle("POST", "/api/block/unfoldBlock", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, unfoldBlock)
	ginServer.Handle("POST", "/api/block/setBlockReminder", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setBlockReminder)
	ginServer.Handle("POST", "/api/block/getHeadingLevelTransaction", model.CheckWebAuth, getHeadingLevelTransaction)
	ginServer.Handle("POST", "/api/block/getHeadingDeleteTransaction", model.CheckWebAuth, getHeadingDeleteTransaction)
	ginServer.Handle("POST", "/api/block/getHeadingInsertTransaction", model.CheckWebAuth, getHeadingInsertTransaction)
	ginServer.Handle("POST", "/api/block/getHeadingChildrenIDs", model.CheckWebAuth, getHeadingChildrenIDs)
	ginServer.Handle("POST", "/api/block/getHeadingChildrenDOM", model.CheckWebAuth, getHeadingChildrenDOM)
	ginServer.Handle("POST", "/api/block/swapBlockRef", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, swapBlockRef)
	ginServer.Handle("POST", "/api/block/transferBlockRef", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, transferBlockRef)
	ginServer.Handle("POST", "/api/block/getBlockSiblingID", model.CheckWebAuth, getBlockSiblingID)
	ginServer.Handle("POST", "/api/block/getBlockRelevantIDs", model.CheckWebAuth, getBlockRelevantIDs)
	ginServer.Handle("POST", "/api/block/getBlockTreeInfos", model.CheckWebAuth, getBlockTreeInfos)
	ginServer.Handle("POST", "/api/block/checkBlockRef", model.CheckWebAuth, checkBlockRef)
	ginServer.Handle("POST", "/api/block/appendHeadingChildren", model.CheckWebAuth, appendHeadingChildren)

	ginServer.Handle("POST", "/api/file/getFile", model.CheckWebAuth, getFile)
	ginServer.Handle("POST", "/api/file/putFile", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, putFile)
	ginServer.Handle("POST", "/api/file/copyFile", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, copyFile)
	ginServer.Handle("POST", "/api/file/globalCopyFiles", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, globalCopyFiles)
	ginServer.Handle("POST", "/api/file/removeFile", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeFile)
	ginServer.Handle("POST", "/api/file/renameFile", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameFile)
	ginServer.Handle("POST", "/api/file/readDir", model.CheckWebAuth, readDir)
	ginServer.Handle("POST", "/api/file/getUniqueFilename", model.CheckWebAuth, getUniqueFilename)

	ginServer.Handle("POST", "/api/ref/refreshBacklink", model.CheckWebAuth, refreshBacklink)
	ginServer.Handle("POST", "/api/ref/getBacklink", model.CheckWebAuth, getBacklink)
	ginServer.Handle("POST", "/api/ref/getBacklink2", model.CheckWebAuth, getBacklink2)
	ginServer.Handle("POST", "/api/ref/getBacklinkDoc", model.CheckWebAuth, getBacklinkDoc)
	ginServer.Handle("POST", "/api/ref/getBackmentionDoc", model.CheckWebAuth, getBackmentionDoc)

	ginServer.Handle("POST", "/api/attr/getBookmarkLabels", model.CheckWebAuth, getBookmarkLabels)
	ginServer.Handle("POST", "/api/attr/resetBlockAttrs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, resetBlockAttrs)
	ginServer.Handle("POST", "/api/attr/setBlockAttrs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setBlockAttrs)
	ginServer.Handle("POST", "/api/attr/batchSetBlockAttrs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchSetBlockAttrs)
	ginServer.Handle("POST", "/api/attr/getBlockAttrs", model.CheckWebAuth, getBlockAttrs)
	ginServer.Handle("POST", "/api/attr/batchGetBlockAttrs", model.CheckWebAuth, batchGetBlockAttrs)

	ginServer.Handle("POST", "/api/cloud/getCloudSpace", model.CheckWebAuth, model.CheckAdminRole, getCloudSpace)

	ginServer.Handle("POST", "/api/sync/setSyncEnable", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncEnable)
	ginServer.Handle("POST", "/api/sync/setSyncInterval", model.CheckWebAuth, setSyncInterval)
	ginServer.Handle("POST", "/api/sync/setSyncPerception", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncPerception)
	ginServer.Handle("POST", "/api/sync/setSyncGenerateConflictDoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncGenerateConflictDoc)
	ginServer.Handle("POST", "/api/sync/setSyncMode", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncMode)
	ginServer.Handle("POST", "/api/sync/setSyncProvider", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncProvider)
	ginServer.Handle("POST", "/api/sync/setSyncProviderS3", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncProviderS3)
	ginServer.Handle("POST", "/api/sync/setSyncProviderWebDAV", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncProviderWebDAV)
	ginServer.Handle("POST", "/api/sync/setSyncProviderLocal", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSyncProviderLocal)
	ginServer.Handle("POST", "/api/sync/setCloudSyncDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setCloudSyncDir)
	ginServer.Handle("POST", "/api/sync/createCloudSyncDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createCloudSyncDir)
	ginServer.Handle("POST", "/api/sync/removeCloudSyncDir", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeCloudSyncDir)
	ginServer.Handle("POST", "/api/sync/listCloudSyncDir", model.CheckWebAuth, listCloudSyncDir)
	ginServer.Handle("POST", "/api/sync/performSync", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, performSync)
	ginServer.Handle("POST", "/api/sync/performBootSync", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, performBootSync)
	ginServer.Handle("POST", "/api/sync/getBootSync", model.CheckWebAuth, getBootSync)
	ginServer.Handle("POST", "/api/sync/getSyncInfo", model.CheckWebAuth, getSyncInfo)
	ginServer.Handle("POST", "/api/sync/exportSyncProviderS3", model.CheckWebAuth, model.CheckAdminRole, exportSyncProviderS3)
	ginServer.Handle("POST", "/api/sync/importSyncProviderS3", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importSyncProviderS3)
	ginServer.Handle("POST", "/api/sync/exportSyncProviderWebDAV", model.CheckWebAuth, model.CheckAdminRole, exportSyncProviderWebDAV)
	ginServer.Handle("POST", "/api/sync/importSyncProviderWebDAV", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importSyncProviderWebDAV)

	ginServer.Handle("POST", "/api/inbox/getShorthands", model.CheckWebAuth, model.CheckAdminRole, getShorthands)
	ginServer.Handle("POST", "/api/inbox/getShorthand", model.CheckWebAuth, model.CheckAdminRole, getShorthand)
	ginServer.Handle("POST", "/api/inbox/removeShorthands", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeShorthands)

	ginServer.Handle("POST", "/api/extension/copy", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, extensionCopy)

	ginServer.Handle("POST", "/api/clipboard/readFilePaths", model.CheckWebAuth, model.CheckAdminRole, readFilePaths)

	ginServer.Handle("POST", "/api/asset/uploadCloud", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, uploadCloud)
	ginServer.Handle("POST", "/api/asset/insertLocalAssets", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, insertLocalAssets)
	ginServer.Handle("POST", "/api/asset/resolveAssetPath", model.CheckWebAuth, resolveAssetPath)
	ginServer.Handle("POST", "/api/asset/upload", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, model.Upload)
	ginServer.Handle("POST", "/api/asset/setFileAnnotation", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setFileAnnotation)
	ginServer.Handle("POST", "/api/asset/getFileAnnotation", model.CheckWebAuth, getFileAnnotation)
	ginServer.Handle("POST", "/api/asset/getUnusedAssets", model.CheckWebAuth, getUnusedAssets)
	ginServer.Handle("POST", "/api/asset/getMissingAssets", model.CheckWebAuth, getMissingAssets)
	ginServer.Handle("POST", "/api/asset/removeUnusedAsset", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeUnusedAsset)
	ginServer.Handle("POST", "/api/asset/removeUnusedAssets", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeUnusedAssets)
	ginServer.Handle("POST", "/api/asset/getDocImageAssets", model.CheckWebAuth, getDocImageAssets)
	ginServer.Handle("POST", "/api/asset/getDocAssets", model.CheckWebAuth, getDocAssets)
	ginServer.Handle("POST", "/api/asset/renameAsset", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameAsset)
	ginServer.Handle("POST", "/api/asset/getImageOCRText", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, getImageOCRText)
	ginServer.Handle("POST", "/api/asset/setImageOCRText", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setImageOCRText)
	ginServer.Handle("POST", "/api/asset/ocr", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, ocr)
	ginServer.Handle("POST", "/api/asset/fullReindexAssetContent", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, fullReindexAssetContent)
	ginServer.Handle("POST", "/api/asset/statAsset", model.CheckWebAuth, model.CheckAdminRole, statAsset)

	ginServer.Handle("POST", "/api/export/exportNotebookMd", model.CheckWebAuth, model.CheckAdminRole, exportNotebookMd)
	ginServer.Handle("POST", "/api/export/exportMds", model.CheckWebAuth, model.CheckAdminRole, exportMds)
	ginServer.Handle("POST", "/api/export/exportMd", model.CheckWebAuth, model.CheckAdminRole, exportMd)
	ginServer.Handle("POST", "/api/export/exportSY", model.CheckWebAuth, model.CheckAdminRole, exportSY)
	ginServer.Handle("POST", "/api/export/exportNotebookSY", model.CheckWebAuth, model.CheckAdminRole, exportNotebookSY)
	ginServer.Handle("POST", "/api/export/exportMdContent", model.CheckWebAuth, model.CheckAdminRole, exportMdContent)
	ginServer.Handle("POST", "/api/export/exportHTML", model.CheckWebAuth, model.CheckAdminRole, exportHTML)
	ginServer.Handle("POST", "/api/export/exportPreviewHTML", model.CheckWebAuth, model.CheckAdminRole, exportPreviewHTML)
	ginServer.Handle("POST", "/api/export/exportMdHTML", model.CheckWebAuth, model.CheckAdminRole, exportMdHTML)
	ginServer.Handle("POST", "/api/export/exportDocx", model.CheckWebAuth, model.CheckAdminRole, exportDocx)
	ginServer.Handle("POST", "/api/export/processPDF", model.CheckWebAuth, model.CheckAdminRole, processPDF)
	ginServer.Handle("POST", "/api/export/preview", model.CheckWebAuth, exportPreview)
	ginServer.Handle("POST", "/api/export/exportResources", model.CheckWebAuth, model.CheckAdminRole, exportResources)
	ginServer.Handle("POST", "/api/export/exportAsFile", model.CheckWebAuth, model.CheckAdminRole, exportAsFile)
	ginServer.Handle("POST", "/api/export/exportData", model.CheckWebAuth, model.CheckAdminRole, exportData)
	ginServer.Handle("POST", "/api/export/exportDataInFolder", model.CheckWebAuth, model.CheckAdminRole, exportDataInFolder)
	ginServer.Handle("POST", "/api/export/exportTempContent", model.CheckWebAuth, model.CheckAdminRole, exportTempContent)
	ginServer.Handle("POST", "/api/export/exportBrowserHTML", model.CheckWebAuth, model.CheckAdminRole, exportBrowserHTML)
	ginServer.Handle("POST", "/api/export/export2Liandi", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, export2Liandi)
	ginServer.Handle("POST", "/api/export/exportReStructuredText", model.CheckWebAuth, model.CheckAdminRole, exportReStructuredText)
	ginServer.Handle("POST", "/api/export/exportAsciiDoc", model.CheckWebAuth, model.CheckAdminRole, exportAsciiDoc)
	ginServer.Handle("POST", "/api/export/exportTextile", model.CheckWebAuth, model.CheckAdminRole, exportTextile)
	ginServer.Handle("POST", "/api/export/exportOPML", model.CheckWebAuth, model.CheckAdminRole, exportOPML)
	ginServer.Handle("POST", "/api/export/exportOrgMode", model.CheckWebAuth, model.CheckAdminRole, exportOrgMode)
	ginServer.Handle("POST", "/api/export/exportMediaWiki", model.CheckWebAuth, model.CheckAdminRole, exportMediaWiki)
	ginServer.Handle("POST", "/api/export/exportODT", model.CheckWebAuth, model.CheckAdminRole, exportODT)
	ginServer.Handle("POST", "/api/export/exportRTF", model.CheckWebAuth, model.CheckAdminRole, exportRTF)
	ginServer.Handle("POST", "/api/export/exportEPUB", model.CheckWebAuth, model.CheckAdminRole, exportEPUB)
	ginServer.Handle("POST", "/api/export/exportAttributeView", model.CheckWebAuth, model.CheckAdminRole, exportAttributeView)

	ginServer.Handle("POST", "/api/import/importStdMd", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importStdMd)
	ginServer.Handle("POST", "/api/import/importZipMd", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importZipMd)
	ginServer.Handle("POST", "/api/import/importData", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importData)
	ginServer.Handle("POST", "/api/import/importSY", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importSY)

	ginServer.Handle("POST", "/api/convert/pandoc", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, pandoc)

	ginServer.Handle("POST", "/api/template/render", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renderTemplate)
	ginServer.Handle("POST", "/api/template/docSaveAsTemplate", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, docSaveAsTemplate)
	ginServer.Handle("POST", "/api/template/renderSprig", model.CheckWebAuth, renderSprig)

	ginServer.Handle("POST", "/api/transactions", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, performTransactions)

	ginServer.Handle("POST", "/api/setting/setAccount", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAccount)
	ginServer.Handle("POST", "/api/setting/setEditor", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setEditor)
	ginServer.Handle("POST", "/api/setting/setExport", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setExport)
	ginServer.Handle("POST", "/api/setting/setFiletree", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setFiletree)
	ginServer.Handle("POST", "/api/setting/setSearch", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSearch)
	ginServer.Handle("POST", "/api/setting/setKeymap", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setKeymap)
	ginServer.Handle("POST", "/api/setting/setAppearance", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAppearance)
	ginServer.Handle("POST", "/api/setting/getCloudUser", model.CheckWebAuth, getCloudUser)
	ginServer.Handle("POST", "/api/setting/logoutCloudUser", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, logoutCloudUser)
	ginServer.Handle("POST", "/api/setting/login2faCloudUser", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, login2faCloudUser)
	ginServer.Handle("POST", "/api/setting/setEmoji", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setEmoji)
	ginServer.Handle("POST", "/api/setting/setFlashcard", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setFlashcard)
	ginServer.Handle("POST", "/api/setting/setAI", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setAI)
	ginServer.Handle("POST", "/api/setting/setBazaar", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setBazaar)
	ginServer.Handle("POST", "/api/setting/setPublish", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setPublish)
	ginServer.Handle("POST", "/api/setting/getPublish", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, getPublish)
	ginServer.Handle("POST", "/api/setting/refreshVirtualBlockRef", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, refreshVirtualBlockRef)
	ginServer.Handle("POST", "/api/setting/addVirtualBlockRefInclude", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, addVirtualBlockRefInclude)
	ginServer.Handle("POST", "/api/setting/addVirtualBlockRefExclude", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, addVirtualBlockRefExclude)
	ginServer.Handle("POST", "/api/setting/setSnippet", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setConfSnippet)
	ginServer.Handle("POST", "/api/setting/setEditorReadOnly", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setEditorReadOnly)

	ginServer.Handle("POST", "/api/graph/resetGraph", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, resetGraph)
	ginServer.Handle("POST", "/api/graph/resetLocalGraph", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, resetLocalGraph)
	ginServer.Handle("POST", "/api/graph/getGraph", model.CheckWebAuth, getGraph)
	ginServer.Handle("POST", "/api/graph/getLocalGraph", model.CheckWebAuth, getLocalGraph)

	ginServer.Handle("POST", "/api/bazaar/getBazaarPlugin", model.CheckWebAuth, getBazaarPlugin)
	ginServer.Handle("POST", "/api/bazaar/getInstalledPlugin", model.CheckWebAuth, getInstalledPlugin)
	ginServer.Handle("POST", "/api/bazaar/installBazaarPlugin", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, installBazaarPlugin)
	ginServer.Handle("POST", "/api/bazaar/uninstallBazaarPlugin", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, uninstallBazaarPlugin)
	ginServer.Handle("POST", "/api/bazaar/getBazaarWidget", model.CheckWebAuth, getBazaarWidget)
	ginServer.Handle("POST", "/api/bazaar/getInstalledWidget", model.CheckWebAuth, getInstalledWidget)
	ginServer.Handle("POST", "/api/bazaar/installBazaarWidget", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, installBazaarWidget)
	ginServer.Handle("POST", "/api/bazaar/uninstallBazaarWidget", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, uninstallBazaarWidget)
	ginServer.Handle("POST", "/api/bazaar/getBazaarIcon", model.CheckWebAuth, getBazaarIcon)
	ginServer.Handle("POST", "/api/bazaar/getInstalledIcon", model.CheckWebAuth, getInstalledIcon)
	ginServer.Handle("POST", "/api/bazaar/installBazaarIcon", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, installBazaarIcon)
	ginServer.Handle("POST", "/api/bazaar/uninstallBazaarIcon", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, uninstallBazaarIcon)
	ginServer.Handle("POST", "/api/bazaar/getBazaarTemplate", model.CheckWebAuth, getBazaarTemplate)
	ginServer.Handle("POST", "/api/bazaar/getInstalledTemplate", model.CheckWebAuth, getInstalledTemplate)
	ginServer.Handle("POST", "/api/bazaar/installBazaarTemplate", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, installBazaarTemplate)
	ginServer.Handle("POST", "/api/bazaar/uninstallBazaarTemplate", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, uninstallBazaarTemplate)
	ginServer.Handle("POST", "/api/bazaar/getBazaarTheme", model.CheckWebAuth, getBazaarTheme)
	ginServer.Handle("POST", "/api/bazaar/getInstalledTheme", model.CheckWebAuth, getInstalledTheme)
	ginServer.Handle("POST", "/api/bazaar/installBazaarTheme", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, installBazaarTheme)
	ginServer.Handle("POST", "/api/bazaar/uninstallBazaarTheme", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, uninstallBazaarTheme)
	ginServer.Handle("POST", "/api/bazaar/getBazaarPackageREAME", model.CheckWebAuth, getBazaarPackageREAME)
	ginServer.Handle("POST", "/api/bazaar/getUpdatedPackage", model.CheckWebAuth, getUpdatedPackage)
	ginServer.Handle("POST", "/api/bazaar/batchUpdatePackage", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, batchUpdatePackage)

	ginServer.Handle("POST", "/api/repo/initRepoKey", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, initRepoKey)
	ginServer.Handle("POST", "/api/repo/initRepoKeyFromPassphrase", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, initRepoKeyFromPassphrase)
	ginServer.Handle("POST", "/api/repo/resetRepo", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, resetRepo)
	ginServer.Handle("POST", "/api/repo/purgeRepo", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, purgeRepo)
	ginServer.Handle("POST", "/api/repo/purgeCloudRepo", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, purgeCloudRepo)
	ginServer.Handle("POST", "/api/repo/importRepoKey", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, importRepoKey)
	ginServer.Handle("POST", "/api/repo/createSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createSnapshot)
	ginServer.Handle("POST", "/api/repo/tagSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, tagSnapshot)
	ginServer.Handle("POST", "/api/repo/checkoutRepo", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, checkoutRepo)
	ginServer.Handle("POST", "/api/repo/getRepoSnapshots", model.CheckWebAuth, getRepoSnapshots)
	ginServer.Handle("POST", "/api/repo/getRepoTagSnapshots", model.CheckWebAuth, getRepoTagSnapshots)
	ginServer.Handle("POST", "/api/repo/removeRepoTagSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeRepoTagSnapshot)
	ginServer.Handle("POST", "/api/repo/getCloudRepoTagSnapshots", model.CheckWebAuth, getCloudRepoTagSnapshots)
	ginServer.Handle("POST", "/api/repo/getCloudRepoSnapshots", model.CheckWebAuth, getCloudRepoSnapshots)
	ginServer.Handle("POST", "/api/repo/removeCloudRepoTagSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeCloudRepoTagSnapshot)
	ginServer.Handle("POST", "/api/repo/uploadCloudSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, uploadCloudSnapshot)
	ginServer.Handle("POST", "/api/repo/downloadCloudSnapshot", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, downloadCloudSnapshot)
	ginServer.Handle("POST", "/api/repo/diffRepoSnapshots", model.CheckWebAuth, model.CheckAdminRole, diffRepoSnapshots)
	ginServer.Handle("POST", "/api/repo/openRepoSnapshotDoc", model.CheckWebAuth, model.CheckAdminRole, openRepoSnapshotDoc)
	ginServer.Handle("POST", "/api/repo/getRepoFile", model.CheckWebAuth, getRepoFile)
	ginServer.Handle("POST", "/api/repo/setRepoIndexRetentionDays", model.CheckWebAuth, model.CheckAdminRole, setRepoIndexRetentionDays)
	ginServer.Handle("POST", "/api/repo/setRetentionIndexesDaily", model.CheckWebAuth, model.CheckAdminRole, setRetentionIndexesDaily)

	ginServer.Handle("POST", "/api/riff/createRiffDeck", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, createRiffDeck)
	ginServer.Handle("POST", "/api/riff/renameRiffDeck", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, renameRiffDeck)
	ginServer.Handle("POST", "/api/riff/removeRiffDeck", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeRiffDeck)
	ginServer.Handle("POST", "/api/riff/getRiffDecks", model.CheckWebAuth, model.CheckAdminRole, getRiffDecks)
	ginServer.Handle("POST", "/api/riff/addRiffCards", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, addRiffCards)
	ginServer.Handle("POST", "/api/riff/removeRiffCards", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeRiffCards)
	ginServer.Handle("POST", "/api/riff/getRiffDueCards", model.CheckWebAuth, model.CheckAdminRole, getRiffDueCards)
	ginServer.Handle("POST", "/api/riff/getTreeRiffDueCards", model.CheckWebAuth, model.CheckAdminRole, getTreeRiffDueCards)
	ginServer.Handle("POST", "/api/riff/getNotebookRiffDueCards", model.CheckWebAuth, model.CheckAdminRole, getNotebookRiffDueCards)
	ginServer.Handle("POST", "/api/riff/reviewRiffCard", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reviewRiffCard)
	ginServer.Handle("POST", "/api/riff/skipReviewRiffCard", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, skipReviewRiffCard)
	ginServer.Handle("POST", "/api/riff/getRiffCards", model.CheckWebAuth, model.CheckAdminRole, getRiffCards)
	ginServer.Handle("POST", "/api/riff/getTreeRiffCards", model.CheckWebAuth, model.CheckAdminRole, getTreeRiffCards)
	ginServer.Handle("POST", "/api/riff/getNotebookRiffCards", model.CheckWebAuth, model.CheckAdminRole, getNotebookRiffCards)
	ginServer.Handle("POST", "/api/riff/resetRiffCards", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, resetRiffCards)
	ginServer.Handle("POST", "/api/riff/batchSetRiffCardsDueTime", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, batchSetRiffCardsDueTime)
	ginServer.Handle("POST", "/api/riff/getRiffCardsByBlockIDs", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, getRiffCardsByBlockIDs)

	ginServer.Handle("POST", "/api/notification/pushMsg", model.CheckWebAuth, model.CheckAdminRole, pushMsg)
	ginServer.Handle("POST", "/api/notification/pushErrMsg", model.CheckWebAuth, model.CheckAdminRole, pushErrMsg)

	ginServer.Handle("POST", "/api/snippet/getSnippet", model.CheckWebAuth, getSnippet)
	ginServer.Handle("POST", "/api/snippet/setSnippet", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setSnippet)
	ginServer.Handle("POST", "/api/snippet/removeSnippet", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, removeSnippet)

	ginServer.Handle("POST", "/api/av/renderAttributeView", model.CheckAuth, renderAttributeView)
	ginServer.Handle("POST", "/api/av/renderHistoryAttributeView", model.CheckAuth, model.CheckAdminRole, renderHistoryAttributeView)
	ginServer.Handle("POST", "/api/av/renderSnapshotAttributeView", model.CheckAuth, model.CheckAdminRole, renderSnapshotAttributeView)
	ginServer.Handle("POST", "/api/av/getAttributeViewKeys", model.CheckAuth, getAttributeViewKeys)
	ginServer.Handle("POST", "/api/av/setAttributeViewBlockAttr", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, setAttributeViewBlockAttr)
	ginServer.Handle("POST", "/api/av/batchSetAttributeViewBlockAttrs", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, batchSetAttributeViewBlockAttrs)
	ginServer.Handle("POST", "/api/av/searchAttributeView", model.CheckAuth, model.CheckReadonly, searchAttributeView)
	ginServer.Handle("POST", "/api/av/getAttributeView", model.CheckAuth, model.CheckReadonly, getAttributeView)
	ginServer.Handle("POST", "/api/av/searchAttributeViewRelationKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, searchAttributeViewRelationKey)
	ginServer.Handle("POST", "/api/av/searchAttributeViewNonRelationKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, searchAttributeViewNonRelationKey) // 请勿使用，该端点计划于 2026 年 6 月 30 日后删除 https://github.com/siyuan-note/siyuan/issues/15727
	ginServer.Handle("POST", "/api/av/searchAttributeViewRollupDestKeys", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, searchAttributeViewRollupDestKeys)
	ginServer.Handle("POST", "/api/av/getAttributeViewFilterSort", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, getAttributeViewFilterSort)
	ginServer.Handle("POST", "/api/av/addAttributeViewKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, addAttributeViewKey)
	ginServer.Handle("POST", "/api/av/removeAttributeViewKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, removeAttributeViewKey)
	ginServer.Handle("POST", "/api/av/sortAttributeViewViewKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, sortAttributeViewViewKey)
	ginServer.Handle("POST", "/api/av/sortAttributeViewKey", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, sortAttributeViewKey)
	ginServer.Handle("POST", "/api/av/addAttributeViewBlocks", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, addAttributeViewBlocks)
	ginServer.Handle("POST", "/api/av/removeAttributeViewBlocks", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, removeAttributeViewBlocks)
	ginServer.Handle("POST", "/api/av/getAttributeViewPrimaryKeyValues", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, getAttributeViewPrimaryKeyValues)
	ginServer.Handle("POST", "/api/av/setDatabaseBlockView", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, setDatabaseBlockView)
	ginServer.Handle("POST", "/api/av/getMirrorDatabaseBlocks", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, getMirrorDatabaseBlocks)
	ginServer.Handle("POST", "/api/av/getAttributeViewKeysByAvID", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, getAttributeViewKeysByAvID)
	ginServer.Handle("POST", "/api/av/getAttributeViewKeysByID", model.CheckAuth, getAttributeViewKeysByID)
	ginServer.Handle("POST", "/api/av/duplicateAttributeViewBlock", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, duplicateAttributeViewBlock)
	ginServer.Handle("POST", "/api/av/appendAttributeViewDetachedBlocksWithValues", model.CheckAuth, model.CheckAdminRole, model.CheckReadonly, appendAttributeViewDetachedBlocksWithValues)
	ginServer.Handle("POST", "/api/av/getCurrentAttrViewImages", model.CheckAuth, getCurrentAttrViewImages)
	ginServer.Handle("POST", "/api/av/changeAttrViewLayout", model.CheckAuth, changeAttrViewLayout)
	ginServer.Handle("POST", "/api/av/setAttrViewGroup", model.CheckAuth, setAttrViewGroup)
	ginServer.Handle("POST", "/api/av/batchReplaceAttributeViewBlocks", model.CheckAuth, batchReplaceAttributeViewBlocks)
	ginServer.Handle("POST", "/api/av/getAttributeViewAddingBlockDefaultValues", model.CheckAuth, getAttributeViewAddingBlockDefaultValues)
	ginServer.Handle("POST", "/api/av/getAttributeViewBoundBlockIDsByItemIDs", model.CheckAuth, getAttributeViewBoundBlockIDsByItemIDs)
	ginServer.Handle("POST", "/api/av/getAttributeViewItemIDsByBoundIDs", model.CheckAuth, getAttributeViewItemIDsByBoundIDs)

	ginServer.Handle("POST", "/api/ai/chatGPT", model.CheckWebAuth, model.CheckAdminRole, chatGPT)
	ginServer.Handle("POST", "/api/ai/chatGPTWithAction", model.CheckWebAuth, model.CheckAdminRole, chatGPTWithAction)
	ginServer.Handle("POST", "/api/ai/chat", model.CheckWebAuth, model.CheckAdminRole, chat)

	// 新增向量化和AI文档分析API
	ginServer.Handle("POST", "/api/ai/vectorizeBlock", model.CheckWebAuth, vectorizeBlock)
	ginServer.Handle("POST", "/api/ai/batchVectorizeNotebook", model.CheckWebAuth, batchVectorizeNotebook)
	ginServer.Handle("POST", "/api/ai/semanticSearch", model.CheckWebAuth, semanticSearch)
	ginServer.Handle("POST", "/api/ai/generateNotebookSummary", model.CheckWebAuth, generateNotebookSummary)
	ginServer.Handle("POST", "/api/ai/getNotebookSummary", model.CheckWebAuth, getNotebookSummary)

	// 新增向量化配置管理API
	ginServer.Handle("POST", "/api/ai/getEmbeddingConfig", model.CheckWebAuth, model.CheckAdminRole, getEmbeddingConfig)
	ginServer.Handle("POST", "/api/ai/setEmbeddingConfig", model.CheckWebAuth, model.CheckAdminRole, setEmbeddingConfig)
	ginServer.Handle("POST", "/api/ai/getEmbeddingModels", model.CheckWebAuth, model.CheckAdminRole, getEmbeddingModels)
	ginServer.Handle("POST", "/api/ai/testEmbeddingConnection", model.CheckWebAuth, model.CheckAdminRole, testEmbeddingConnection)

	ginServer.Handle("POST", "/api/petal/loadPetals", model.CheckWebAuth, loadPetals)
	ginServer.Handle("POST", "/api/petal/setPetalEnabled", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, setPetalEnabled)

	ginServer.Any("/api/network/echo", model.CheckWebAuth, model.CheckAdminRole, echo)
	ginServer.Handle("POST", "/api/network/forwardProxy", model.CheckWebAuth, model.CheckAdminRole, forwardProxy)

	ginServer.Handle("GET", "/ws/broadcast", model.CheckWebAuth, model.CheckAdminRole, broadcast)
	ginServer.Handle("GET", "/es/broadcast/subscribe", model.CheckWebAuth, model.CheckAdminRole, broadcastSubscribe)

	ginServer.Handle("POST", "/api/broadcast/publish", model.CheckWebAuth, model.CheckAdminRole, broadcastPublish)
	ginServer.Handle("POST", "/api/broadcast/postMessage", model.CheckWebAuth, model.CheckAdminRole, postMessage)
	ginServer.Handle("POST", "/api/broadcast/getChannels", model.CheckWebAuth, model.CheckAdminRole, getChannels)
	ginServer.Handle("POST", "/api/broadcast/getChannelInfo", model.CheckWebAuth, model.CheckAdminRole, getChannelInfo)

	ginServer.Handle("POST", "/api/archive/zip", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, zip)
	ginServer.Handle("POST", "/api/archive/unzip", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, unzip)

	ginServer.Handle("POST", "/api/ui/reloadUI", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadUI)
	ginServer.Handle("POST", "/api/ui/reloadIcon", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadIcon)
	ginServer.Handle("POST", "/api/ui/reloadAttributeView", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadAttributeView)
	ginServer.Handle("POST", "/api/ui/reloadProtyle", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadProtyle)
	ginServer.Handle("POST", "/api/ui/reloadFiletree", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadFiletree)
	ginServer.Handle("POST", "/api/ui/reloadTag", model.CheckWebAuth, model.CheckAdminRole, model.CheckReadonly, reloadTag)

	// Web认证API - 多用户登录注册系统（不需要原有认证）
	ginServer.Handle("POST", "/api/web/auth/login", webAuthLogin)
	ginServer.Handle("POST", "/api/web/auth/register", webAuthRegister)
	ginServer.Handle("POST", "/api/web/auth/unified-login", webAuthUnifiedLogin)
	ginServer.Handle("GET", "/api/web/auth/unified-status", webAuthUnifiedStatus)
	ginServer.Handle("GET", "/api/web/auth/health", webAuthHealth)
	ginServer.Handle("POST", "/api/web/auth/verify-token", webAuthVerifyToken)
	ginServer.Handle("POST", "/api/web/auth/refresh-token", webAuthRefreshToken)

	// Web认证API - 需要Web认证的接口
	ginServer.Handle("POST", "/api/web/auth/profile", webAuthMiddleware, webAuthProfile)
	ginServer.Handle("POST", "/api/web/auth/update-profile", webAuthMiddleware, webAuthUpdateProfile)
	ginServer.Handle("POST", "/api/web/auth/change-password", webAuthMiddleware, webAuthChangePassword)
	ginServer.Handle("POST", "/api/web/auth/logout", webAuthMiddleware, webAuthLogout)
}
